/*
 * Copyright 2017-2018 deepbrain.ai, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://deepbrain.ai/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#ifndef APP_EVENT_H
#define APP_EVENT_H

//音乐播放事件
typedef enum APP_EVENT_AUDIO_PLAYER_t
{
	APP_EVENT_AUDIO_PLAYER_BASE = APP_EVENT_BASE_ADDR,
	APP_EVENT_AUDIO_PLAYER_PLAY,
	APP_EVENT_AUDIO_PLAYER_PAUSE,
	APP_EVENT_AUDIO_PLAYER_RESUME,
	APP_EVENT_AUDIO_PLAYER_STOP,
}APP_EVENT_AUDIO_PLAYER_t;

//WIFI事件
typedef enum APP_EVENT_WIFI_t
{
	APP_EVENT_WIFI_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_AUDIO_PLAYER_BASE),
	APP_EVENT_WIFI_DEVICE_INIT_DONE,//wifi初始化完成
	APP_EVENT_WIFI_CONNECTING,		//连接中 
	APP_EVENT_WIFI_CONNECTED,		//已连接
	APP_EVENT_WIFI_DISCONNECTED, 	//断开连接
	APP_EVENT_WIFI_CONFIG,			//WIFI-AP配网
	APP_EVENT_WIFI_AIRKISS_CONFIG,	//WIFI-AIRKISS配网
	APP_EVENT_WIFI_AIRKISS_RECV_OK, //WIFI-AIRKISS接收信息成功
	APP_EVENT_WIFI_CONNECT_FAIL,	//连接失败
}APP_EVENT_WIFI_t;

//SDCARD事件
typedef enum APP_EVENT_SDCARD_t
{
	APP_EVENT_SDCARD_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_WIFI_BASE),
	APP_EVENT_SD_CARD_MUSIC_PLAY,
	APP_EVENT_SD_CARD_MUSIC_PREV,
	APP_EVENT_SD_CARD_MUSIC_NEXT,
}APP_EVENT_SDCARD_t;

//POWER MANAGE事件
typedef enum APP_EVENT_POWER_t
{
	APP_EVENT_POWER_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_SDCARD_BASE),
	APP_EVENT_POWER_CHARGING,
	APP_EVENT_POWER_CHARGING_STOP,
	APP_EVENT_POWER_LOW_POWER,
	APP_EVENT_POWER_SHUTDOWN_INSTRUCTION,
}APP_EVENT_POWER_t;

//free talk事件
typedef enum APP_EVENT_FREE_TALK_t
{
	APP_EVENT_FREE_TALK_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_POWER_BASE),
	APP_EVENT_FREE_TALK_RESULT,
	APP_EVENT_FREE_TALK_START_SILENT,	//静默启动
	APP_EVENT_FREE_TALK_START_PROMPT,	//带提示启动
}APP_EVENT_FREE_TALK_t;

//play list
typedef enum APP_EVENT_PLAYLIST_t
{
	APP_EVENT_PLAYLIST_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_FREE_TALK_BASE),
	APP_EVENT_PLAYLIST_REQUEST,
	APP_EVENT_PLAYLIST_PREV,
	APP_EVENT_PLAYLIST_NEXT,
	APP_EVENT_PLAYLIST_STOP,
	APP_EVENT_PLAYLIST_CLEAR,
	APP_EVENT_PLAYLIST_PLAY_STAUTS,
}APP_EVENT_PLAYLIST_t;

//audio input process
typedef enum APP_EVENT_AIP_t
{
	APP_EVENT_AIP_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_PLAYLIST_BASE),
	APP_EVENT_AIP_START_RECORD,
	APP_EVENT_AIP_STOP_RECORD,
}APP_EVENT_AIP_t;

//wechat event
typedef enum APP_EVENT_WECHAT_t
{
	APP_EVENT_WECHAT_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_AIP_BASE),
	APP_EVENT_WECHAT_NEW_MSG,
	APP_EVENT_WECHAT_START,
	APP_EVENT_WECHAT_STOP
}APP_EVENT_WECHAT_t;

//ota event
typedef enum APP_EVENT_OTA_t
{
	APP_EVENT_OTA_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_WECHAT_BASE),
	APP_EVENT_OTA_START,
	APP_EVENT_OTA_STOP,
}APP_EVENT_OTA_t;

//keyboard event
typedef enum APP_EVENT_KEYBOARD_t
{
	APP_EVENT_KEYBOARD_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_OTA_BASE),
	APP_EVENT_KEYBOARD_EVENT,
}APP_EVENT_KEYBOARD_t;

typedef enum APP_EVENT_ASR_SERVICE_t
{
	APP_EVENT_ASR_SERVICE_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_KEYBOARD_BASE),
	APP_EVENT_ASR_SERVICE_NEW_REQUEST,
}APP_EVENT_ASR_SERVICE_t;

typedef enum APP_EVENT_DISPLAY_t
{
	APP_EVENT_DISPLAY_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_ASR_SERVICE_BASE),
	APP_EVENT_DISPLAY_IDLE,
	APP_EVENT_DISPLAY_ENABLE,
	APP_EVENT_DISPLAY_DISABLE,
	APP_EVENT_DISPLAY_PAUSE,
	APP_EVENT_DISPLAY_RESUME,
	APP_EVENT_DISPLAY_TTS_START,
	APP_EVENT_DISPLAY_TTS_STOP,
	APP_EVENT_DISPLAY_TONE_START,
	APP_EVENT_DISPLAY_TONE_STOP,
	APP_EVENT_DISPLAY_MUSIC_START,
	APP_EVENT_DISPLAY_MUSIC_STOP,
	APP_EVENT_DISPLAY_PLAYER_STOP,
	APP_EVENT_DISPLAY_RECORD_START,
	APP_EVENT_DISPLAY_RECORD_STOP,
}APP_EVENT_DISPLAY_t;

//关键词唤醒事件
typedef enum APP_EVENT_KEYWORD_WAKEUP_t
{
	APP_EVENT_KEYWORD_WAKEUP_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_DISPLAY_BASE),
	APP_EVENT_KEYWORD_WAKEUP_NOTIFY,
}APP_EVENT_KEYWORD_WAKEUP_t;

//录音回放事件
typedef enum APP_EVENT_RECORD_PLAYBACK_t
{
	APP_EVENT_RECORD_PLAYBACK_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_KEYWORD_WAKEUP_BASE),
	APP_EVENT_RECORD_PLAYBACK_PLAY,
}APP_EVENT_RECORD_PLAYBACK_t;

//LED灯事件
typedef enum APP_EVENT_LED_CTRL_t
{
	APP_EVENT_LED_CTRL_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_RECORD_PLAYBACK_BASE),
	APP_EVENT_LED_CTRL_IDLE,
	APP_EVENT_LED_CTRL_EYE_ON,						//眼灯亮
	APP_EVENT_LED_CTRL_EYE_OFF,						//眼灯灭
	APP_EVENT_LED_CTRL_EYE_300_MS_FLICKER,			//眼灯300毫秒闪一次
	APP_EVENT_LED_CTRL_EYE_500_MS_FLICKER,			//眼灯500毫秒闪一次
	APP_EVENT_LED_CTRL_EYE_800_MS_FLICKER,			//眼灯800毫秒闪一次
	APP_EVENT_LED_CTRL_EYE_1000_MS_FLICKER,			//眼灯1000毫秒闪一次
	APP_EVENT_LED_CTRL_EYE_3000_MS_FLICKER,			//眼灯3秒闪一次
	APP_EVENT_LED_CTRL_EYE_GRADUAL_CHANGE_FLICKER,	//眼灯渐变式闪烁
	APP_EVENT_LED_CTRL_EAR_ON,						//耳灯亮
	APP_EVENT_LED_CTRL_EAR_OFF,						//耳灯灭
	APP_EVENT_LED_CTRL_EAR_500_MS_FLICKER,			//耳灯500毫秒闪一次
}APP_EVENT_LED_CTRL_t;

//APP BIND DEVICE
typedef enum APP_EVENT_BIND_DEVICE_t
{
	APP_EVENT_BIND_DEVICE_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_LED_CTRL_BASE),
	APP_EVENT_BIND_DEVICE_MSG,
}APP_EVENT_BIND_DEVICE_t;

//memo service
typedef enum APP_EVENT_MEMO_t
{
	APP_EVENT_MEMO_BASE = APP_EVENT_BASE_NEXT(APP_EVENT_BIND_DEVICE_BASE),
	APP_EVENT_MEMO_CANCLE,
}APP_EVENT_MEMO_t;

#endif /*APP_EVENT_H*/
