#ifndef PARTITIONS_CONFIG_H
#define PARTITIONS_CONFIG_H
/*flash分区配置表

flash分区排布：
|----OTA1----|----OTA2----|----CONFIG----|----FAT32----|

*/

#define PARTITIONS_FLASH_SIZE_4M 	4
#define PARTITIONS_FLASH_SIZE_8M 	8
#define PARTITIONS_FLASH_SIZE_16M 	16

//分区大小
#define PARTITIONS_TOTAL_SIZE 	(PARTITIONS_FLASH_SIZE_8M*1024*1024)

//flash配置参数分区 128kb
#define PARTITIONS_ADDR_CONFIG 	0x7e0000
#define PARTITIONS_SIZE_CONFIG 	0x20000

//配置参数1 4kb
#define PARTITIONS_ADDR_CONFIG_1 PARTITIONS_ADDR_CONFIG
#define PARTITIONS_SIZE_CONFIG_1 (0x1000)

//唤醒词license信息存储，flash最后4kb区域
#define PARTITIONS_SIZE_WAKEUP_AUTH	(0x1000)
#define PARTITIONS_ADDR_WAKEUP_AUTH	(PARTITIONS_TOTAL_SIZE - PARTITIONS_SIZE_WAKEUP_AUTH)

#endif

