#ifndef __ARRAY_MUSIC_H__
#define __ARRAY_MUSIC_H__
 #include <stdio.h>
#include <string.h>

typedef struct
{
    int audio_len;
    char *audio_data;
    char *audio_name;
} FLASH_MUSIC_DATA_T;

typedef enum
{
    FLASH_MUSIC_2_DYY_NOT_HEAR_CLEARLY_PLEASE_REPEAT,
    FLASH_MUSIC_2_DYY_PLEASE_INSERT_THE_TFCARD,
    FLASH_MUSIC_BAI_KE,
    FLASH_MUSIC_BATTERY_LOW,
    FLASH_MUSIC_BATTERY_POWER_LOW,
    FLASH_MUSIC_BEI_WANG_YI_GUO_QI,
    FLASH_MUSIC_BEI_WANG_YI_TIAN_JIA,
    FLASH_MUSIC_BIAN_MA_SHI_BAI,
    FLASH_MUSIC_BYEBYE,
    FLASH_MUSIC_CHAT_SHORT_AUDIO,
    FLASH_MUSIC_CHAT_TONE,
    FLASH_MUSIC_CLOSE_FREE_TALK,
    FLASH_MUSIC_DEVICE_SLEEP,
    FLASH_MUSIC_DNS_JIE_XI_SHI_BAI,
    FLASH_MUSIC_DYY_I_CAN_NOT_DO_THIS,
    FLASH_MUSIC_DYY_DEVICE_ACTIVATE_FAIL,
    FLASH_MUSIC_DYY_DEVICE_ACTIVATE_OK,
    FLASH_MUSIC_DYY_ERROR_PLEASE_TRY_AGAIN_LATER,
    FLASH_MUSIC_DYY_IT_IS_DONE,
    FLASH_MUSIC_DYY_MATCHING_NETWORK_FAILURE,
    FLASH_MUSIC_DYY_NEW_VERSION_AVAILABLE,
    FLASH_MUSIC_DYY_NO_MUSIC_PLAY,
    FLASH_MUSIC_DYY_NO_PLAY_RESOURCE,
    FLASH_MUSIC_DYY_UPGRADE_DONE,
    FLASH_MUSIC_DYY_UPGRADE_FAILED,
    FLASH_MUSIC_DYY_UPGRADING_TTS,
    FLASH_MUSIC_DYY_VOL_MAX,
    FLASH_MUSIC_DYY_VOL_MIN,
    FLASH_MUSIC_DYY_VOLUME_ALREADY_HIGHEST,
    FLASH_MUSIC_DYY_VOLUME_ALREADY_LOWEST,
    FLASH_MUSIC_DYY_VOLUME_CHANGE_OK,
    FLASH_MUSIC_DYY_VOLUME_DOWN,
    FLASH_MUSIC_DYY_VOLUME_UP,
    FLASH_MUSIC_DYY_WAIT_FOR_SD_SCAN,
    FLASH_MUSIC_EMO_EATING_TIME,
    FLASH_MUSIC_EMO_HUNGRY,
    FLASH_MUSIC_EMO_I_CAN_DO_ANYTHING,
    FLASH_MUSIC_EMO_IM_BEST_ROBOT,
    FLASH_MUSIC_EMO_IM_GOING_TO_BANZHUAN,
    FLASH_MUSIC_EMO_IM_GOING_TO_HOMEWORK,
    FLASH_MUSIC_EMO_IM_GOING_TO_LEARNING,
    FLASH_MUSIC_EMO_IM_GOING_TO_SLEEP,
    FLASH_MUSIC_EMO_LEARN_TO_HELP_PARENTS,
    FLASH_MUSIC_EMO_LIAO_DIAN_SHEN_ME_NE,
    FLASH_MUSIC_EMO_WHY_NOT_TALKING,
    FLASH_MUSIC_EQUIPMENT_UPGRADING,
    FLASH_MUSIC_ER_GE,
    FLASH_MUSIC_FU_WU_QI_CUO_WU,
    FLASH_MUSIC_GU_SHI,
    FLASH_MUSIC_GUO_XUE,
    FLASH_MUSIC_HUAN_YING_SHI_YONG_LE_DOU,
    FLASH_MUSIC_IM_MICKEY_MOUSE,
    FLASH_MUSIC_KE_TANG,
    FLASH_MUSIC_KEY_PRESS,
    FLASH_MUSIC_MEMO_ADDED,
    FLASH_MUSIC_MESSAGE_ALERT,
    FLASH_MUSIC_MSG_SEND,
    FLASH_MUSIC_MUSIC_PAUSE,
    FLASH_MUSIC_MUSIC_PLAY,
    FLASH_MUSIC_NETWORK_CONFIG,
    FLASH_MUSIC_NETWORK_CONNECT_BEFORE_USE,
    FLASH_MUSIC_NETWORK_CONNECT_FAILURE,
    FLASH_MUSIC_NETWORK_CONNECT_SUCCESS,
    FLASH_MUSIC_NETWORK_CONNECTING,
    FLASH_MUSIC_NETWORK_DISCONNECTED,
    FLASH_MUSIC_NEXT_SONG,
    FLASH_MUSIC_NO_MUSIC,
    FLASH_MUSIC_NO_MUSIC_SOURCE,
    FLASH_MUSIC_NO_TF_CARD,
    FLASH_MUSIC_NOT_HEAR_CLEARLY_PLEASE_REPEAT,
    FLASH_MUSIC_OFF_SEE_YOU_NEXT_TIME,
    FLASH_MUSIC_POOR_NETWORK_SIGNAL,
    FLASH_MUSIC_POWER_OFF,
    FLASH_MUSIC_PREV_SONG,
    FLASH_MUSIC_QIN_ZI,
    FLASH_MUSIC_SEND_FAIL,
    FLASH_MUSIC_SEND_SUCCESS,
    FLASH_MUSIC_START_CHARGING,
    FLASH_MUSIC_TF_CARD_INSERTED,
    FLASH_MUSIC_TF_CARD_PULL_OUT,
    FLASH_MUSIC_TONE_AI_NO_SPEAK_00,
    FLASH_MUSIC_TONE_AI_NO_SPEAK_01,
    FLASH_MUSIC_TONE_AI_NO_SPEAK_02,
    FLASH_MUSIC_TONE_AI_NO_SPEAK_03,
    FLASH_MUSIC_TONE_HAO_DE,
    FLASH_MUSIC_TONE_NO_NET,
    FLASH_MUSIC_TONE_SLEEP,
    FLASH_MUSIC_TOUCH_001,
    FLASH_MUSIC_TOUCH_002,
    FLASH_MUSIC_TOUCH_003,
    FLASH_MUSIC_TOUCH_004,
    FLASH_MUSIC_TOUCH_005,
    FLASH_MUSIC_TOUCH_006,
    FLASH_MUSIC_TOUCH_007,
    FLASH_MUSIC_UPDATE_FAIL,
    FLASH_MUSIC_UPGRADE_COMPLETE,
    FLASH_MUSIC_UPGRADING_MUSIC,
    FLASH_MUSIC_WAIT_FOR_SD_SCAN,
    FLASH_MUSIC_WAKEUP_NI_HAO_ZHU_REN,
    FLASH_MUSIC_WAKEUP_SHA_SHI,
    FLASH_MUSIC_WAKEUP_WO_LAI_LA,
    FLASH_MUSIC_WAKEUP_WO_ZAI,
    FLASH_MUSIC_WAKEUP_ZAI,
    FLASH_MUSIC_WAKEUP_ZHONG_ME_LA,
    FLASH_MUSIC_WANG_LUO_BU_JIA,
    FLASH_MUSIC_WANG_LUO_BU_KE_YONG,
    FLASH_MUSIC_WECHAT_SHORT_AUDIO,
    FLASH_MUSIC_WELCOME,
    FLASH_MUSIC_WIFI_CONNECTED,
    FLASH_MUSIC_WIFI_CONNECTING,
    FLASH_MUSIC_WIFI_DISCONNECTED,
    FLASH_MUSIC_XI_TONG_CUO_WU,
    FLASH_MUSIC_XIA_ZAI,
    FLASH_MUSIC_YIN_YUE,
    FLASH_MUSIC_YING_YU,
}FLASH_MUSIC_INDEX_T;


char *get_flash_music_data(int index);

char *get_flash_music_name(int index);

char *get_flash_music_name_ex(int index);

int get_flash_music_size(int index);

int get_flash_music_max_subscript();

#endif /*__ARRAY_MUSIC_H__*/
